# Generated by Django 4.0.6 on 2022-07-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_messagemodel_alter_productmodel_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='special',
            field=models.TextField(default=None, max_length=10),
        ),
    ]
