# Generated by Django 4.0.6 on 2022-07-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=models.CharField(default='No Description Avilable', max_length=225),
        ),
    ]
